[build]
  command = "zola build --base-url $URL"
  publish = "public"

[build.environment]
  ZOLA_VERSION = "0.23.3"

[context.deploy-preview]
  command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "zola build --base-url $DEPLOY_PRIME_URL"
